name: Deploy Angular App to DigitalOcean

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy on DigitalOcean
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root
            if [ ! -d frontend-rico ]; then
              git clone https://github.com/Emerson-Portugal/frontend-rico.git
            fi
            cd frontend-rico
            git pull origin develop
            npm install --force
            npm run build --configuration=sertchile

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/sertchile/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html/
            sudo systemctl restart nginx
