name: Deploy Angular App to DigitalOcean

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy on DigitalOcean
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd frontend-rico/
            git pull origin develop
            npm install --force
            npm run build --configuration=sertchile

            # Asegúrate de que el directorio destino exista
            sudo mkdir -p /var/www/html/

            # Borra el contenido anterior
            sudo rm -rf /var/www/html/*

            # Copia los archivos compilados
            sudo cp -r dist/sertchile/* /var/www/html/

            # Establece permisos correctos
            sudo chown -R www-data:www-data /var/www/html/

            # Reinicia Nginx para aplicar cambios
            sudo systemctl restart nginx
